### ISSUE TITLE
chore(): rename repository name for OSS

### ISSUE THREAD

**Issue by rdlabo** [peregrinejs/iOS#4]
Forking this repository will result in username/iOS. This makes it difficult to find targets for OSS activities.

![スクリーンショット 2022-12-13 午前11 45 19](https://user-images.githubusercontent.com/9690024/207213771-36ccd767-3ad2-4876-9327-f4ebe53b3118.png)

I suggest to change 'peregrinejs/peregrine-iOS'.

**Comment by imhoffd** [comment]
This is a great idea because it's better for forks _and_ it looks better in XCode instead of just seeing "iOS" under frameworks. Thanks! The repo has been renamed and the docs have been updated.

**Comment by imhoffd** [comment]
Uh oh, I can't publish under the Pod name "Peregrine" because it's in use by [this project](https://github.com/BinaryParadise/Peregrine).

I emailed the owner in hopes that they're not using it anymore.
